apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-node
spec:
  replicas: 3
  selector:
    app: hello-node
  template:
    metadata:
      name: hello-node
      labels:
        app: hello-node
    spec:
      containers:
      - name: hello-node
        image: smugcloud/hello-node
        ports:
        - containerPort: 9000
---

kind: Service
apiVersion: v1
metadata:
  name: hello-node
spec:
  type: LoadBalancer
  selector:
    app: hello-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
