apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-node
spec:
  replicas: 10
  selector:
    app: hello-node
  template:
    metadata:
      name: hello-node
      labels:
        app: hello-node
    spec:
      containers:
      - name: hello-node
        image: smugcloud/hello-node
        ports:
        - containerPort: 9000
---

kind: Service
apiVersion: v1
metadata:
  name: hello-node
spec:
  selector:
    app: hello-node
  ports:
    - protocol: TCP
      port: 80
      nodePort: 32000
      targetPort: 9000
  type: NodePort