apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: probe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: probe
    spec:
      containers:
      - name: probe
        image: smugcloud/probe
        ports:
        - containerPort: 9000