apiVersion: v1
kind: ReplicationController
metadata:
  name: weather
spec:
  replicas: 3
  selector:
    app: openweather
  template:
    metadata:
      name: openweather
      labels:
        app: openweather
    spec:
      containers:
      - name: openweather
        image: smugcloud/openweather
        ports:
        - containerPort: 9090
        env:
        - name: api_key
          valueFrom:
            secretKeyRef:
              name: api-key
              key: api_key
---

apiVersion: v1
kind: Secret
metadata:
  name: api-key
type: Opaque
data:
  api_key: NGJkZjhkYjU2ZWVmNjdiNDczOWIwNTk1NjlmNDliNDg=
---

kind: Service
apiVersion: v1
metadata:
  name: weather
spec:
  selector:
    app: openweather
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
      nodePort: 31100
  type: NodePort
